[tool.poetry]
name = "check-dependencies"
version = "0.10.0"
description = ""
authors = ["Micha Scholl <schollm-git@gmx.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8"
toml = "*"

[tool.poetry.group.dev.dependencies]
pytest = "^6.2"
mypy = "^1.10.0"
black = "^24.4.2"
isort = "^5.13.2"
pylint = "^3.2.3"
pytest-cov = "^5.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ['py39']

[tool.isort]
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER']
multi_line_output = 3
line_length = 88
include_trailing_comma = 'True'
profile = "black"
